Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Patient_Management_Project.Functions;
using Patient_Management_Project.Models;
using static Patient_Management_Project.Helpers.SessionManager;
using Patient_Management_Project.Models.DAL;

namespace Patient_Management_Project.Controllers
{
    public class UserController : Controller
    {
        
       
        [SessionAuthorize]
        public ActionResult ManageUser()
        {

            try
            {
                var userID = LoginCache[(UserKey)Session["UserKey"]].UserID;
                var users = new Authentication().GetUsers(userID);

                ViewBag.Users = users;

                return View();
            }
            catch (Exception)
            {
                ViewBag.ErrorMessage = Messages.GENERAL_ERROR;
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult UserRegister(ViewUser obj)
        {

            var profileRequest = new Authentication.UserMetaData
            {

                FirstName = Common.textInfo.ToTitleCase(obj.FirstName),
                LastName = Common.textInfo.ToTitleCase(obj.LastName),
                EmailAddress = obj.EmailAddress.ToLower(),
                Username = $"{obj.FirstName.Substring(0, 1).Trim().ToLower()}{Helpers.SanitiseInput(obj.LastName.Trim()).ToLower()}", // generate a username
                UserPassword = obj.InitialPassword,
                UserRole = obj.UserRole,
                CreatedOn = DateTime.Now,
                CreatedBy = "Self Register",
                Active = true


            };


            try
            {
                var response = new Authentication().CreateUserProfile(profileRequest);
                if (!string.IsNullOrEmpty(response.Username))
                {
                    ModelState.Clear();
                    Session["ErrorMessage"] = string.Empty;
                    Session["SuccessMessage"]= string.Format(Messages.USER_REGISTERED_SUCCESSFULLY, response.Username);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    Session["SuccessMessage"] = string.Empty;
                    Session["ErrorMessage"] = response.PossibleErrorMessage;
                    return RedirectToAction("Index", "Home");
                }
            }
            catch (Exception)
            {
                ViewBag.ErrorMessage = Messages.GENERAL_ERROR;
               
                return RedirectToAction("Index", "Home");
            }

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionAuthorize]
        public ActionResult NewUser(ViewUser obj)
        {

            if (ModelState.IsValid)
            {
                var profileRequest = new Authentication.UserMetaData
                {

                    FirstName = Common.textInfo.ToTitleCase(obj.FirstName),
                    LastName = Common.textInfo.ToTitleCase(obj.LastName),
                    EmailAddress = obj.EmailAddress.ToLower(),
                    Username = $"{obj.FirstName.Substring(0, 1).Trim().ToLower()}{Helpers.SanitiseInput(obj.LastName.Trim()).ToLower()}", // generate a username
                    UserPassword = obj.InitialPassword,
                    UserRole= obj.UserRole,
                    CreatedOn = DateTime.Now,
                    CreatedBy= LoginCache[(UserKey)Session["UserKey"]].Username,
                    Active = true


                };


                try
                {
                    var response = new Authentication().CreateUserProfile(profileRequest);
                    if (!string.IsNullOrEmpty(response.Username))
                    {
                        ModelState.Clear();
                        ViewBag.SuccessMessage = string.Format(Messages.USER_CREATED, response.Username);
                        return RedirectToAction("ManageUser");
                    }
                    else
                    {
                        ViewBag.ErrorMessage = response.PossibleErrorMessage;
                    }
                }
                catch (Exception)
                {
                    ViewBag.ErrorMessage = Messages.GENERAL_ERROR;
                }
            }
            return RedirectToAction("ManageUser");

        }

        public ActionResult GetUser(int id)
        {
            try
            {
                var thisUser = new Authentication().GetUsers(LoginCache[(UserKey)Session["UserKey"]].UserID).ToList().Find(x => x.UserID == id);
                return Json(thisUser, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {

            }

            return View();
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionAuthorize]
        public ActionResult ModifyUser(ViewUser obj)
        {
            try
            {
                var userID = LoginCache[(UserKey)Session["UserKey"]].UserID;
                
                var thisUser = new Authentication.ModifyUserMetaData
                {
                    UserID = obj.UserID,
                    Username = obj.Username,
                    EmailAddress = obj.EmailAddress,
                    FirstName = Common.textInfo.ToTitleCase(obj.FirstName),
                    LastName = Common.textInfo.ToTitleCase(obj.LastName),
                    UserRole = obj.UserRole
                };
                var response = new Authentication().ModifyUserProfile(thisUser);

                if (response.IsSuccess)
                {
                    ModelState.Clear();
                    ViewBag.SuccessMessage = string.Format(Messages.OPERATION_COMPLETED_SUCCESSFULLY);
                    return RedirectToAction("ManageUser");
                }
                else
                {
                    ViewBag.ErrorMessage = response.PossibleErrorMessage;
                    return RedirectToAction("ManageUser");
                }


            }
            catch (Exception)
            {
                ViewBag.ErrorMessage = Messages.GENERAL_ERROR;
                return RedirectToAction("ManageUser");
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [SessionAuthorize]
        public ActionResult ResetPassword(ViewUser obj)
        {
            try
            {

                var resetPassword = new Authentication.ResetUserPasswordMetaData
                {
                    NewPassword = obj.InitialPassword,
                    ConfirmNewPassword = obj.ConfirmNewPassword,
                    UserID = Convert.ToInt32(obj.UserID),
                    Username = obj.Username

                };

                var response = new Authentication().ResetPassword(resetPassword);

                if (response.IsSuccess)
                {
                    ModelState.Clear();
                    ViewBag.SuccessMessage = string.Format(Messages.OPERATION_COMPLETED_SUCCESSFULLY);
                    return RedirectToAction("ManageUser");
                }
                else
                {
                    ViewBag.ErrorMessage = response.PossibleErrorMessage;
                    return RedirectToAction("ManageUser");
                }

            }
            catch (Exception)
            {
                ViewBag.ErrorMessage = Messages.GENERAL_ERROR;
                return RedirectToAction("ManageUser");
            }

        }

        [SessionAuthorize]
        public ActionResult DeactivateUser(int id)
        {
            try
            {
                
                var response = new Authentication().DeactivateUser(id);

                if (response.IsSuccess)
                {
                    ModelState.Clear();
                    ViewBag.SuccessMessage = string.Format(Messages.OPERATION_COMPLETED_SUCCESSFULLY);
                    return RedirectToAction("ManageUser");
                }
                else
                {
                    ViewBag.ErrorMessage = Messages.GENERAL_ERROR;
                    return RedirectToAction("ManageUser");
                }

            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return RedirectToAction("ManageUser");
            }

        }

        [SessionAuthorize]
        public ActionResult ActivateUser(int id)
        {
            try
            {
                var response = new Authentication().ActivateUser(id);

                if (response.IsSuccess)
                {
                    ModelState.Clear();
                    ViewBag.SuccessMessage = string.Format(Messages.OPERATION_COMPLETED_SUCCESSFULLY);
                    return RedirectToAction("ManageUser");
                }
                else
                {
                    ViewBag.ErrorMessage = Messages.GENERAL_ERROR;
                    return RedirectToAction("ManageUser");
                }

            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = ex.Message;
                return RedirectToAction("ManageUser");
            }

        }

        [SessionAuthorize]
        public ActionResult DeleteUser(int id)
        {
            try
            {
                var response =new Authentication().DeleteUser(id);

                if (response.IsSuccess)
                {
                    ModelState.Clear();
                    ViewBag.SuccessMessage = string.Format(Messages.OPERATION_COMPLETED_SUCCESSFULLY);
                    return RedirectToAction("ManageUser");
                }
                else
                {
                    ViewBag.ErrorMessage = Messages.GENERAL_ERROR;
                    return RedirectToAction("ManageUser");
                }

            }
            catch (Exception ex)
            {

Views/Home/ChangePassword.cshtml
@model Patient_Management_Project.Models.ViewChangePassword

@{
    ViewBag.Title = "Change Password";

}


@using (Html.BeginForm("ChangePassword", "Home"))
{
    @Html.AntiForgeryToken()


    <div id="wrapper">
        <div class="main-content container">
            <div class="row small-spacing">
                <div class="col-xs-12">
                    <div class="box-content card white">
                        <h4 class="box-title" style="font-weight:600;line-height:16px;font-size:16px">Change Password</h4>

                        <!-- /.box-title -->
                        <div class="text-success">@ViewBag.SuccessMessage</div>
                        <div class="text-warning">@ViewBag.WarningMessage</div>
                        <div class="error">@ViewBag.ErrorMessage</div>
                        <div class="error">@ViewBag.Unauth</div>
                        <div class="card-content">


                            <div class="form-horizontal">
                                <hr />
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CurrentPassword, "Current Password", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-5">
                                        @Html.EditorFor(model => model.CurrentPassword, new { htmlAttributes = new { @class = "form-control", @maxlength = "50", @type = "password" } })
                                        @Html.ValidationMessageFor(model => model.CurrentPassword, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CurrentPassword, "New Password", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-5">
                                        @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                                        @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CurrentPassword, "Confirm New Password", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-5">
                                        @Html.EditorFor(model => model.ConfirmNewPassword, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                                        @Html.ValidationMessageFor(model => model.ConfirmNewPassword, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        @if (ViewBag.Unauth == null)
                                        {
                                            <input type="submit" value="Change Password" class="frm-submit" />

                                        }
                                        else
                                        {
                                            <input type="submit" value="Change Password" disabled="disabled" class="frm-submit" />
                                        }
                                    </div>
                                </div>
                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

}
@section scripts{
    <script>
        $(document).ready(function () {

            $("label[class='control-label col-md-2']").prop("id", "required");

        });
        </script>
    
}

Views/Home/Index.cshtml
@model Patient_Management_Project.Models.ViewUser
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
}

    <div id="single-wrapper">
        
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()


            <div class="frm-single">
                <div class="inside">
                    <div class="title">
                        <img src="~/assets/images/cliniclogo.png" alt="" style="width: 30%; height: 10%" /> <br>
                        <strong>EGPAF</strong> <br>Patient Management System
                    </div>

                    <div class="frm-title">Login</div>
                    <div class="text-success">@ViewBag.SuccessMessage</div>
                    <div class="error">@ViewBag.ErrorMessage</div>
                    <div class="text-success">@Session["SuccessMessage"]</div>
                    <div class="error">@Session["ErrorMessage"]</div>

                    <div class="form-horizontal">

                        <hr />

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        <div class="frm-input">
                            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "frm-inp", @placeholder = "Username", @autofocus = "autofocus", @type = "text", @autocomplete = "off" } })
                            <i class="fa fa-user frm-ico"></i>
                            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })

                        </div>

                        <div class="frm-input">

                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "frm-inp", @type = "password", @placeholder = "Password" } })
                            <i class="fa fa-lock frm-ico"></i> <br />
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })

                        </div>

                        <button type="submit" class="frm-submit">Login<i class="fa fa-arrow-circle-right"></i></button>

                        <div>A Product of <a style="color:blue;" target="_blank" href="#">EGPAF</a> | Version 1.0.0</div>

                    </div>
                </div>

            </div>
        }
        <p style="font-weight:bolder;color:red; margin-left:40%;margin-top:-1%">

            New user? <button class="btn btn-primary" id="btnNewUser"> Register here </button>

        </p>
    </div>


<!-- Create Modal-->
<div class="modal fade draggable-modal" id="newUser" role="dialog" style="z-index:1100;margin-left:20%">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">New User Registration</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("UserRegister", "User"))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">

                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })



                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2", @id = "required" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter First Name", @maxlength = "50", @required = "required" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2", @id = "required" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Last Name", @maxlength = "50", @required = "required" } })
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2", @id = "required" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control", @placeholder = "Enter Email Address", @maxlength = "50", @type = "email", @required = "required" } })
                            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserRole, htmlAttributes: new { @class = "control-label col-md-2", @id = "required" })
                        <div class="col-md-5">
                            @Html.DropDownListFor(m => m.UserRole, Common.GetSystemRole(), "Please Select", htmlAttributes: new { @class = "form-control", @required = "required" })
                            @Html.ValidationMessageFor(model => model.UserRole, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.InitialPassword, htmlAttributes: new { @class = "control-label col-md-2", @id = "required" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.InitialPassword, new { htmlAttributes = new { @class = "form-control", @maxlength = "50", @type = "password", @required = "required" } })
                            @Html.ValidationMessageFor(model => model.InitialPassword, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ConfirmNewPassword, htmlAttributes: new { @class = "control-label col-md-2", @id = "required" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.ConfirmNewPassword, new { htmlAttributes = new { @class = "form-control", @maxlength = "50", @type = "password", @required = "required" } })
                            @Html.ValidationMessageFor(model => model.ConfirmNewPassword, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div style="margin-left:17%"><input type="submit" value="Register" class="frm-submit" /></div>


                </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>

        $('#btnNewUser').click(function () {

            //Clear text fields

            $("select[name=UserRole]").val("");
            $("input[name=FirstName]").val("");
            $("input[name=LastName]").val("");
            $("input[name=UserID]").val("");
            $("input[name=EmailAddress]").val("");


            $('#newUser').modal({
                backdrop: false,
                show: true
            });

            $('.modal-dialog').draggable({
                handle: ".modal-header"
            });

        });
    </script>
}